### ISSUE TITLE
Allow arbitrary top-level properties to be added to log messages

### ISSUE THREAD

**Issue by jstock** [elastic/ecs-dotnet#239]
**ECS integration/library project(s) (e.g. Elastic.CommonSchema.Serilog)**: 
Elastic.CommonSchema.Serilog

**Is your feature request related to a problem? Please describe.**
We are using Serilog Enrichers to add the following messages to log events:
- service.environment
- service.name
- service.version
- tdx.entity.id
- tdx.entity.partition.id

They're getting added to the logs correctly, but are always being nested under `metadata`. We then added an `EcsTextFormatterConfig().MapCustom()` implementation and were able to make `service.name` and `service.version` display at the root level, but the other 3 are still nested under `metadata`. We also tried mapping them as labels to see if that would help, but those get nested under `labels`.

**Describe the solution you'd like**
Allow custom properties to be added at the root level of log messages, even if there isn't a class defined for it in [EcsDocument](https://github.com/elastic/ecs-dotnet/blob/main/src/Elastic.CommonSchema/EcsDocument.Generated.cs).

**Describe alternatives you've considered**
I've considered adding some kind of mapping rule in Elastic to format these messages after they're received, but would like if this was handled in the log creation phase.

**Additional context**
The following screenshots display example properties on the log events in Elastic

![metadata](https://user-images.githubusercontent.com/7373934/214849281-82ad87bb-9ae8-41a3-9264-34a0ea2f81c6.png)

![labels](https://user-images.githubusercontent.com/7373934/214849316-b14bd1e0-25a2-42fb-9ed0-3c1daccd0a71.png)

![service](https://user-images.githubusercontent.com/7373934/214849337-09d6d92b-554a-41e4-8e3c-9a97a5fe7856.png)

I'd like for the following properties to also be displayed at the root level of log messages:

- service.environment
- tdx.entity.id
- tdx.partition.id

Please let me know if there's any additional information I can provide.

**Comment by Mpdreamz** [comment]
The new version (8.4) which is scheduled to go out soon will do partially what you describe out of the box. 

Known ECS keys will now directly assign to EcsDocument properties e.g `{ServiceEnvironment}` will now correctly set `service.environment` 

For unknown properties its best to use `EcsTextFormatterConfiguration<TEcsDocument>` instead of `EcsTextFormatterConfiguration` and create your own subclass of `EcsDocument` that has a `tdx` property to assign to. 

See these docs on extending EcsDocument:

https://github.com/elastic/ecs-dotnet/tree/main/src/Elastic.CommonSchema#extending-ecsdocument

This also ensures your `EcsDocument` fully round-trips between writing and reading.

**Comment by jstock** [comment]
Great, this is exactly what I needed. Thank you!
