### ISSUE TITLE
[FEATURE] Enable full configuration of `Elastic.Serilog.Sinks` through `appsettings.json`

### ISSUE THREAD

**Issue by nenadvicentic** [elastic/ecs-dotnet#346]
`Serilog` supports full configuration of logging through `appsettings.json` via `Serilog.Settings.Configuration` NuGet package (project is [here](https://github.com/serilog/serilog-settings-configuration))

For example `Serilog.Sinks.Elasticsearch` supports full configuration via `appsettings.json`. This would be an example:

```json
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Elasticsearch" ],
    "MinimumLevel": "Warning,
    "WriteTo": [
      {
        "Name": "Elasticsearch",
        "Args": {
          "nodeUris": "http://localhost:9200",
          "inlineFields": true
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName" ],
    "Properties": {
      "Application": "My app"
    }
  },
}
```

In `Serilog.Sinks.Elasticsearch` this is achieved by exposing extension method for configuration of each of input parameters. Int the code example bellow is simplified extension method, showing only two "Args" parameters used in above JSON configuration file.

```csharp
        public static LoggerConfiguration Elasticsearch(
            this LoggerSinkConfiguration loggerSinkConfiguration,
            string nodeUris,
            // ...
            bool inlineFields = false,
            // ...
            )
```

Full source code of the above extension method can be found [here](https://github.com/serilog-contrib/serilog-sinks-elasticsearch/blob/fbba80b59f7a689da965ad5953554f491925b828/src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs#L150)

**Comment by haggerty-william** [comment]
It seems like there is some support. I can tell at least that it will try to ship logs to elastic with default options if you include a Elasticsearch section in the WriteTo array. Is there anyway to tell what is currently supported?

**Comment by gonace** [comment]
This is the only reason why we're not moving to `Elastic.Serilog.Sinks`, so we're waitng for this implementation 🎉

**Comment by MithrilMan** [comment]
This is really something essential for us too.

**Comment by MithrilMan** [comment]
fyi I've implemented a workaround: create a custom extension that works with appsettings.json
investigating the code on <https://github.com/serilog/serilog-settings-configuration> I've found a way to implement my own extension method that works with my settings, it requires to:

- create an extension method that's compatible with the serilog.settings.configuration alghoritm that looks for extension method to call
- insert it in a proper project whose name contains the "Serilog" word, or add "Using" property under Serilog settings in appsettings.json

In my case, the need was just to configure the endpoint address. Since I was coming from `serilog-sinks-elasticsearch` package that had a `nodeUris` property, I basically just implemented this extension

```
public static class LoggerConfigurationWayExtensions
{
   public static LoggerConfiguration Elasticsearch(this LoggerSinkConfiguration loggerConfiguration, string nodeUris)
      => loggerConfiguration.Elasticsearch([new Uri(nodeUris)]); << da spostare
}
```

The discovery process of serilog, among other peculiarities, involves the extension be named like the sink (so Elasticsearch in this example) and be implemented in a project whose name contains "Serilog" OR the assembly name be included in the "Using" property under "Serilog" settings ( see <https://github.com/serilog/serilog-settings-configuration?tab=readme-ov-file#using-section-and-auto-discovery-of-configuration-assemblies>)

Since my project haven't Serilog word in it, I used the "Using"  like this
![image](https://github.com/elastic/ecs-dotnet/assets/5107375/0ee7cdda-e189-4c92-9614-2685314fb189)

In appsettings I had just to add nodeUris under "Args" property
```
"WriteTo": [
   {
      "Name": "Elasticsearch",
      "Args": {
         "nodeUris": "http://logger-elasticsearch:9200"
      }
   }
]
```

and now my extension gets called, that just calls the original extension method accepting an Uri enumeration.

So, while we wait for an official solution, we can create our own extension that fit our needs

**Comment by aj-scram** [comment]
My company is also looking to switch to elastic apm and this is a major issue for us as well

**Comment by MithrilMan** [comment]
@aj-scram you are welcome, long live the art of making do! :)

**Comment by ReinhardvdBerg** [comment]
I'm trying to migrate lots of projects to Elastic.Serilog.Sinks and am a bit disappointed that out of the box appsettings.json config does not exist yet.

**Comment by darianmh** [comment]
I'm using this config and it works
`  {
    "Name": "Elasticsearch",
    "Args": {
      "nodes": [ "http://elasticsearch:9200" ]
    }
  }`

**Comment by Westat-Transportation** [comment]
My company is also looking at migrating many systems to this package and this is a major blocker for us. I wonder how different the two code bases are, perhaps it would not be too much work to bring over that feature from the now deprecated sink.

**Comment by nenadvicentic** [comment]
> I'm using this config and it works ` { "Name": "Elasticsearch", "Args": { "nodes": [ "http://elasticsearch:9200" ] } }`

I just tested this and it works. However, there are some differences compared to `Serilog.Sinks.Elasticsearch`:

- Log data is inserted via to Kibana data stream feature.
- Log data is stored to index that shows up as `logs-dotnet-default` in "Discovery" section of Kibana.
- `_index` property of a logged JSON message shows different name`"_index": ".ds-logs-dotnet-default-2024.09.10-000001"`. Probably something to do with how data streams work.
- Message format is different compared to `Serilog.Sinks.Elasticsearch`. For example, my custom `Application` property is now stored as `labels.Application`.
- Log data is also visible in "Logs" section of Kibana now.


Bellow is full configuration I used. It uses `Serilog.Sinks.Console` and `Elastic.Serilog.Sinks`. Only `WriteTo` and `Using` sections have been modified, compared to usage of `Serilog.Sinks.Elasticsearch`.

```json
{
  "Serilog": {
    "Using": [ "Elastic.Serilog.Sinks", "Serilog.Sinks.Console" ],
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft.AspNetCore": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "Elasticsearch",
        "Args": {
          "nodes": [ "http://elastichost:9200" ]
        }
      },
      { "Name": "Console" }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName" ],
    "Properties": {
      "Application": "My Application"
    }
  },
}
```

**Comment by Mpdreamz** [comment]
While you could technically configure all the options through: https://github.com/serilog/serilog-settings-configuration?tab=readme-ov-file#nested-configuration-sections, this is more cumbersome than it needs to be and further more not documented at all. 

The full lack of support is mainly as per my own personal preferences as https://github.com/serilog/serilog-settings-configuration [silently eats configuration errors](https://github.com/serilog/serilog-settings-configuration/issues/153) its super easy to misconfigure. 

As per: https://github.com/elastic/ecs-dotnet/pull/441 we now have an overload with all the config options that can be projected easier to `Args: []`. See the PR for full examples. 

Thanks everyone for being vocal around this!
